theme: jekyll-theme-ephesus
title: Elena Di Lavore
description: PhD student at Tallinn University of Technology
photo: <img src="https://github.com/elenadilavore/elenadilavore.github.io/blob/master/profilo.jpg?raw=true" width="100">
